package com.as307.aryaa.ui.screens.medicalid

import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.compose.ui.test.onNodeWithText
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class MedicalIdActivityTest {

    @get:Rule
    val composeTestRule = createAndroidComposeRule<MedicalIdActivity>()

    @Test
    fun activityLaunches_andRendersCard() {
        // Verify that the lock-screen activity displays the card header and key fields
        composeTestRule.onNodeWithText("🆘 MEDICAL ID").assertIsDisplayed()
        composeTestRule.onNodeWithText("BLOOD TYPE").assertIsDisplayed()
        composeTestRule.onNodeWithText("Generated by ARYAA — आर्या").assertIsDisplayed()
    }
}
